config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :games, only: [:index, :show, :new, :create] do
    resources :revisions, only: [:index, :show, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :revisions

  scope :recent, -> { order("updated_at DESC").limit(5) }
  validates :name, :description, :creator_id, presence: true
  belongs_to :creator, class_name: :User

  def text_description
    Nokogiri::HTML(self.description).text
  end

  def standard_created_at
    self.created_at.strftime("%Y.%m.%d")
  end

  def collaborator_count
    collabs = self.revisions.pluck(:collaborator_id)
    nils = collabs.length
    collabs.select! do |collab|
      collab != nil
    end
    nils -= collabs.length
    collabs.uniq.length + nils
  end

  def last_revision
    self.revisions.last
  end

  def self.by_latest_revision
    self.all.sort_by { |game| game.last_revision.created_at}.reverse
  end

  def self.five_latest
    self.by_latest_revision[0..4]
  end

end

app/models/revision.rb
class Revision < ApplicationRecord
  belongs_to :game
  belongs_to :collaborator, class_name: "User", optional: true

  validates_presence_of :name, :description, :game_id

  def text_description
    Nokogiri::HTML(self.description).text
  end

  def standard_created_at
    self.created_at.strftime("%Y.%m.%d")
  end

  def rev_username
    if self.collaborator == nil
      "anonymous"
    else
      self.collaborator.username
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :games, foreign_key: :creator_id
  attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def index
    @games = Game.five_latest
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.sort_by{ |g| g.name.downcase }
  end

  def show
    @game = Game.find_by(id: params[:id])

    if @game
      @latest_game = @game.revisions.last
      render :show
    else
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  end

  def new
    if user_signed_in?
      @game = Game.new
      render :new, :status => 200
    else
      render :file => "#{Rails.root}/public/422.html",  :status => 422
    end
  end

  def create
    @game = Game.new(game_params)

    if user_signed_in?
      @game.update_attributes(creator_id: current_user.id)
      if @game.save
        @revision = Revision.new(game_params)
        @revision.update_attributes(game_id: @game.id)
        @revision.update_attributes(collaborator_id: current_user.id)
        @game.revisions << @revision
        redirect_to game_path(@game)
      else
        render :new
      end
    else
      render :file => "#{Rails.root}/public/422.html",  :status => 422
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :description, :image)
  end
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  def index
    @game = Game.find_by(id: params[:game_id])
    @revisions = @game.revisions
  end

  def show
    p 'RRRR' * 100
    p params
    @game = Game.find_by(id: params[:game_id])
    @revision = @game.revisions.last
  end

  def new
    @game = Game.find_by(id: params[:game_id])
    @revision = Revision.new
  end

  def create
    @game = Game.find_by(id: params[:game_id])
    @revision = Revision.new(revision_params)
    @revision.update_attributes(game_id: params[:game_id])

    if user_signed_in?
      @revision.update_attributes(collaborator_id: current_user.id)
    end

    if @revision.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  private

  def revision_params
    params.require(:revision).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<% if !user_signed_in? %>
  <div class="buttons">
    <div class="button">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="buttons">
    <div class="button">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Create New Game", new_game_path %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    </div>
  </div>
<% end %>

app/views/application/index.html.erb
<h2>Site Manifesto</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed eros posuere, varius velit ut, eleifend tortor. Sed egestas pretium nisi quis blandit. Integer efficitur nibh nulla, in molestie arcu posuere ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus fringilla, eros nec auctor ultrices, lacus leo suscipit lorem, nec faucibus libero risus non ipsum. Donec mattis luctus nibh, nec vulputate odio malesuada vitae. Vestibulum semper quis purus at ultricies. Mauris elementum sem mauris, quis rhoncus turpis facilisis at. Nulla facilisi.</p>

<h2>Recent Games</h2>
<div class="recent-games">
  <% @games.each do |game| %>
    <span class="title"><%= link_to game.last_revision.name, game %></span><br>
    <span class="creator"> created by <%= game.creator.username %> on <%= game.standard_created_at %></span><br>
    <span class="blurb"><%= truncate(game.last_revision.text_description, length: 200) %></span><br>
  <% end %>
</div>

<h4><a href="/games">List all game ideas</a></h4>

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@game.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :description, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>
    Revisions:
    <ul>
      <%= f.fields_for :revisions do |revisions_form| %>
        <li>
          <%= revisions_form.label :name %><br>
          <%= revisions_form.text_field :name %><br>

          <%= revisions_form.label :description %><br>
          <%= revisions_form.text_field :description %><br>
        </li>
      <% end %>
    </ul>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h2>Edit Game Idea</h2>

<%= render "games/form" %>

app/views/games/index.html.erb
<h2>All Game Ideas</h2>
<div class="list-all-games">
  <% @games.each do |game| %>
    <span class="title"><%= link_to game.last_revision.name, game %></span><br>
    <span class="creator"> created by <%= game.creator.username %> on <%= game.standard_created_at %></span><br>
    <span class="blurb"><%= truncate(game.last_revision.text_description, length: 200) %></span><br>
  <% end %>
</div>

app/views/games/new.html.erb
<h2>Create New Game Idea</h2>

<%= render "games/form" %>

app/views/games/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <% if @game.revisions.length > 1 %>
    <p>Revision Count: <%= @game.revisions.count - 1 %>,
      <%= link_to "See Revision History",  game_revisions_path(@game) %>,
      <%= link_to "Add a Revision!", new_game_revision_path(@game) %>
    </p>
    <p>Collaborators: <%= @game.collaborator_count %></p>
  <% else %>
    <p>No Revisions Yet: <%= link_to "Create a Revision!", new_game_revision_path(@game) %></p>
  <% end %>

  <h2 class="text-center"><%= @latest_game.name %></h2>
  <h5 class="text-center">Created: <%= @game.created_at.strftime('%b %d, %Y') %></h5>
  <h5 class="text-center">Last Updated: <%= @latest_game.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @latest_game.description %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roundtable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<div class="nav-container">
  <div class="nav">
    <%= render "application/nav" %>
  </div>
</div>
<div class="title-container">
  <h1 id="banner-text">RoundTable</h1>
  <p class="title-note">The idea-pedia for board game creations</p>
</div>
  <body>
    <div class="container">
      <div class="main-content">

        <% flash.each do |name, message| %>
          <%= content_tag(:div, message, class: "alert") %>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <div class="footer-container">
      <p class="foot-note">InnoTrove Industries</p>
    </div>
  </body>
</html>

app/views/revisions/_form.html.erb
<%= simple_form_for(@revision, url: game_revisions_path(@game)) do |f| %>
  <% if @revision.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@revision.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @revision.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name, input_html: {value: "#{@game.revisions.last.name}"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :description, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, input_html: {value: "#{@game.revisions.last.description}"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/revisions/index.html.erb
<h2>Revisions for <%= @game.name %></h2>
  <%= link_to "Add a Revision!", new_game_revision_path(@game) %><br>
  <%= link_to "Return to Game View", game_path(@game) %><br><br>
<div class="recent-games">
  <% @revisions.each_with_index do |revision, index| %>
    <span class="title"> <%= "#{index+1}. " %> <%= link_to revision.name, game_revision_path(revision.game, revision) %></span><br>
    <span class="creator"> created by <%= revision.rev_username %> on <%= revision.standard_created_at %></span><br>
    <span class="blurb"><%= truncate(revision.text_description, length: 200) %></span><br>
  <% end %>

</div>

app/views/revisions/new.html.erb
<h2>Create Revision of Game Idea</h2>

<%= render "revisions/form" %>

app/views/revisions/show.html.erb
<div>
  <h2><%= @revision.name %></h2>
  <h5><%= @revision.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @revision.description %></div>
</div>
<br>
<br>
<%= link_to "Current Version", game_path(@revision.game) %>
<br>
<br>
<%= link_to "Show all Revisions", game_revisions_path(@revision.game) %>